os:
- windows
- linux
- osx
language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
script:
- cargo build --verbose --workspace
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: 'target/debug/polar_send_training.exe'
  on:
    repo: slysherz/polar-send-training
  skip_cleanup: 'true'
